print('Hola mundo')
print(2*9)
numero1 = input('Escribe un numero: ')
numero2 = input('Escribe un numero: ')
resultado = int(numero1) * int(numero2)
print('El resultado de la multiplicacion es : ', resultado)